2020-06-16 14:37:20,830 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:40]
2020-06-16 16:14:43,817 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:42]
2020-06-16 16:22:05,991 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:42]
2020-06-17 14:12:57,535 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:16:39,599 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:17:32,351 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:18:19,888 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:19:15,550 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:21:39,269 ERROR : Exception on /index [GET] [inc:\users\user\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\microblog\app\routes.py", line 36, in index
    return render_template('index.html', title = _('Home'), form=form, posts = posts.items, next_url=next_url,prev_url=prev_url)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\microblog\app\templates\index.html", line 22, in template
    {{_(Older posts)}} <span aria-hidden="true">&rarr;</span>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'posts'
2020-06-17 14:22:18,108 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:25:34,844 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:25:39,720 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:26:03,896 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:44:12,139 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:45:09,006 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:45:31,978 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:47:31,818 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:48:24,237 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:54:25,004 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 14:59:56,276 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:03:34,498 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:11:04,089 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:12:05,948 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:14:54,369 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:17:27,328 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:20:28,971 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:21:52,023 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:25:40,103 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:26:21,007 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:26:38,458 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:28:05,927 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:29:01,026 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:29:18,040 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:31:56,748 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:38:58,553 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 15:41:39,994 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-17 16:07:26,020 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-18 11:04:40,088 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-18 11:05:00,028 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-18 15:27:03,660 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:45]
2020-06-19 16:55:15,491 INFO : Microblog startup [inC:\Users\User\microblog\app\__init__.py:71]
2020-06-19 16:55:18,909 ERROR : Exception on / [GET] [inc:\users\user\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\microblog\venv\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\users\user\microblog\venv\lib\site-packages\flask_login\login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "c:\users\user\microblog\venv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "c:\users\user\microblog\venv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\microblog\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\user\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
